YubikitDemo/src/main/java/com/yubico/yubikit/demo/BaseYubikeyFragment.kt
YubikitDemo/src/main/java/com/yubico/yubikit/demo/YubikeyViewModel.kt
YubikitDemo/src/main/java/com/yubico/yubikit/demo/mgmt/ManagementFragment.kt
YubikitDemo/src/main/java/com/yubico/yubikit/demo/mgmt/ManagementViewModel.kt
YubikitDemo/src/main/java/com/yubico/yubikit/demo/raw/YubikeySmartcardFragment.kt
management/src/main/java/com/yubico/yubikit/configurator/YubiKeyConfigurationApplication.java
management/src/main/java/com/yubico/yubikit/management/ManagementApplication.java
oath/src/main/java/com/yubico/yubikit/oath/OathApplication.java
piv/src/main/java/com/yubico/yubikit/piv/PivApplication.java

Since we create connection and selecting YubiKey applet in constructor of application (to avoid user calling extra select() method). We need to close connection if selection failed. So that user can reuse connection for another applet.
Also small improvements on demo: 
- show firmware version of the key in YubiKey Settings (managements applet) for NEO keys.
- hide snackbars if detected usb communication unless we get error that permissions are required
- clean up raw communication log when YubiKey was ejected

Close connection in case if application was not selected

---

YubikitDemo/src/main/java/com/yubico/yubikit/demo/BaseYubikeyFragment.kt
YubikitDemo/src/main/java/com/yubico/yubikit/demo/YubikeyViewModel.kt
YubikitDemo/src/main/java/com/yubico/yubikit/demo/oath/CredentialListAdapter.kt
YubikitDemo/src/main/java/com/yubico/yubikit/demo/settings/Ramps.kt
YubikitDemo/src/main/res/xml/settings.xml
fido/build.gradle
fido/src/test/java/com/yubico/yubikit/utils/PackageUtilsTest.java
fidodemo/src/test/java/com/yubico/yubikit/demo/fido/Fido2ViewModelTest.kt
oath/build.gradle
oath/src/main/java/com/yubico/yubikit/oath/Code.java
oath/src/main/java/com/yubico/yubikit/oath/Credential.java
oath/src/main/java/com/yubico/yubikit/oath/OathApplication.java
oath/src/main/java/com/yubico/yubikit/oath/OathApplicationInfo.java
oath/src/test/java/com/yubico/yubikit/oath/CredentialDataTest.java
otp/src/main/java/com/yubico/yubikit/otp/OtpActivity.java
yubikit/README.md
yubikit/build.gradle
yubikit/src/main/java/com/yubico/yubikit/YubiKitManager.java
yubikit/src/main/java/com/yubico/yubikit/transport/nfc/NfcConfiguration.java
yubikit/src/main/java/com/yubico/yubikit/transport/nfc/NfcDeviceManager.java
yubikit/src/main/java/com/yubico/yubikit/transport/usb/UsbConfiguration.java
yubikit/src/main/java/com/yubico/yubikit/transport/usb/UsbDeviceManager.java
yubikit/src/main/java/com/yubico/yubikit/transport/usb/UsbIso7816Connection.java
yubikit/src/main/java/com/yubico/yubikit/transport/usb/UsbSessionListener.java
yubikit/src/main/java/com/yubico/yubikit/utils/ILogger.java
yubikit/src/main/java/com/yubico/yubikit/utils/Logger.java
yubikit/src/test/java/com/yubico/yubikit/YubikitManagerTest.java

Created UsbConfiguration and NfcConfiguration classes that need to be passed when start discovery of YubiKey connection.
Added ability to turn off sound for NFC tag discovery. And also Skipping NDEF check (for most of YubiKey connections we don't need NDEF tag, so skipping it's check might optimize the speed of discovery of NFC tag)
Added onRequestPermissionsResult callback for usbManager that will be invoked when permissions were granted or denied by user (addressing https://github.com/Yubico/yubikit-android/issues/8)

Provide extensible approach to configure NFC and USB discovery

---

otp/src/main/AndroidManifest.xml
otp/src/main/java/com/yubico/yubikit/otp/OtpParser.java
otp/src/test/java/com/yubico/yubikit/otp/OtpParserTest.java
yubikit/README.md

OTP module can parse NDEF tag value from URL, NdefMessage or Tag.

Allow to parse OTP tag value from different objects

---

YubikitDemo/src/main/java/com/yubico/yubikit/demo/BaseYubikeyFragment.kt
YubikitDemo/src/main/java/com/yubico/yubikit/demo/YubikeyViewModel.kt
YubikitDemo/src/main/java/com/yubico/yubikit/demo/exceptions/InvalidCertDataException.kt
YubikitDemo/src/main/java/com/yubico/yubikit/demo/exceptions/UsbDeviceNotFoundException.java
YubikitDemo/src/main/java/com/yubico/yubikit/demo/piv/PivFragment.kt
YubikitDemo/src/main/java/com/yubico/yubikit/demo/piv/PivViewModel.kt
YubikitDemo/src/main/java/com/yubico/yubikit/demo/raw/SecCertificate.kt
YubikitDemo/src/main/java/com/yubico/yubikit/demo/raw/YubikeySmartcardViewModel.kt
piv/src/main/java/com/yubico/yubikit/piv/PivApplication.java

Added verification logic within demo when signing data to make sure that signature returned is valid/authentic.
Switched from [javax Certificate](https://developer.android.com/reference/javax/security/cert/X509Certificate) to [java Certificate](https://developer.android.com/reference/java/security/cert/X509Certificate), because it seems like the way [JDK wants to move to](https://bugs.openjdk.java.net/browse/JDK-8227395)
Addressing issue: https://github.com/Yubico/yubikit-android/issues/15

Fix typo in pkcs1.15 padding implementation for RSA signature

---

AndroidDemo/src/main/java/com/yubico/yubikit/android/app/ui/oath/OathViewModel.kt
oath/src/main/java/com/yubico/yubikit/oath/OathSession.java

Adds `public boolean isLocked()` method to OathSession to get the current lock state.
Once the OathSession is successfully unlocked  with `unlock` the method returns `false` until the session is closed or `reset()` is called.

add OathSession isLocked

---

oath/src/main/java/com/yubico/yubikit/oath/OathSession.java

This rewrites the calculateCodes method to be more readable and clear in what it is doing, and in so removed the incorrect handling of TOTP credentials that require touch and have a period != 30.

Fix OATH calculateCodes for TOTP credentials with requireTouch and period != 30.

---

AndroidDemo/src/main/java/com/yubico/yubikit/android/app/ui/piv/PivCertificateFragment.kt
piv/src/main/java/com/yubico/yubikit/piv/jca/PivAlgorithmParameterSpec.java
piv/src/main/java/com/yubico/yubikit/piv/jca/PivKeyPairGeneratorSpi.java
testing/src/main/java/com/yubico/yubikit/testing/piv/PivDeviceTests.java
testing/src/main/java/com/yubico/yubikit/testing/piv/PivJcaDeviceTests.java

This adds KeyType to the PivAlgorithmParameterSpec, and forbids the use of the initialize(keySize) initializer.

Fix KeyPairGenerator spec

---

AndroidDemo/build.gradle
android/build.gradle
android/src/androidTest/java/com/yubico/yubikit/android/ExampleInstrumentedTest.java
android/src/main/java/com/yubico/yubikit/android/transport/usb/UsbYubiKeyDevice.java
android/src/main/java/com/yubico/yubikit/android/transport/usb/connection/ConnectionManager.java
android/src/test/java/com/yubico/yubikit/android/YubikitManagerTest.java
android/src/test/java/com/yubico/yubikit/android/transport/usb/connection/UsbSmartCardConnectionTest.java
build.gradle
management/src/main/java/com/yubico/yubikit/management/DeviceInfo.java
oath/src/main/java/com/yubico/yubikit/oath/OathSession.java
piv/src/main/java/com/yubico/yubikit/piv/jca/PivEcSignatureSpi.java
piv/src/main/java/com/yubico/yubikit/piv/jca/PivRsaSignatureSpi.java

Fixes following issues:
- [ANDSDK-82](https://yubico.atlassian.net/browse/ANDSDK-82) - DeviceInfo serial number wrongly set to 0
- [ANDSDK-84](https://yubico.atlassian.net/browse/ANDSDK-84) - No static method encodeBase64String
- [ANDSDK-101](https://yubico.atlassian.net/browse/ANDSDK-101) - bump Kotlin version
- [ANDSDK-102](https://yubico.atlassian.net/browse/ANDSDK-102) - fix gradle warning
- [ANDSDK-85](https://yubico.atlassian.net/browse/ANDSDK-85) - suppress warnings
- [ANDSDK-86](https://yubico.atlassian.net/browse/ANDSDK-86) - suppress warnings

Fixes to 2.1.0-alpha.1 (1)

---

.github/workflows/scan.yml
pom.gradle

We are going to change the default branch name for this project to `main`.
This PR changes `master` to `main` where appropriate.

Rename default git branch to main

---

android/src/main/java/com/yubico/yubikit/android/transport/nfc/NfcSmartCardConnection.java
android/src/main/java/com/yubico/yubikit/android/transport/usb/connection/UsbSmartCardConnection.java
core/src/main/java/com/yubico/yubikit/core/smartcard/SmartCardConnection.java
piv/src/main/java/com/yubico/yubikit/piv/PivSession.java

This PR fixes a bug where the SDK used Extended length APDUs on incompatible NFC adapters. 
[Android documentation](https://developer.android.com/reference/android/nfc/tech/IsoDep#isExtendedLengthApduSupported()) says following about Extended length APDUs:
> Standard APDUs have a 1-byte length field, allowing a maximum of 255 payload bytes, which results in a maximum APDU length of 261 bytes.
> 
> Extended length APDUs have a 3-byte length field, allowing 65535 payload bytes.
> 
> Some NFC adapters, like the one used in the Nexus S and the Galaxy Nexus do not support extended length APDUs. They are expected to be well-supported in the future though. Use this method to check for extended length APDU support.
The issue is easily reproduced on a "compatible" device (without Extended APDUs …

Use Extended length APDUs only on compatible adapters and devices

---

.github/workflows/android.yml
android/publish.gradle
doc/publish.adoc
publish.gradle

When using version string for release versions (without -SNAPSHOT postfix) signing is executed automatically during `publish` and `publishToMavenLocal` gradle tasks. This makes most of the CI builds fail in release branch, because the CI nodes don't have signing configuration/possibility.
This PR adds an option to opt out from signing by using environmental variable `NO_GPG_SIGN` set to `true`.
Example:
`NO_GPG_SIGN=true ./gradlew publishToMavenLocal`
When `NO_GPG_SIGN` is not defined or is not `true`, gradle will execute signing tasks.

Conditionally disable release signing 

---

AndroidDemo/src/main/java/com/yubico/yubikit/android/app/ui/yubiotp/YubiOtpFragment.kt

`launch(null)` passes null to non-null input parameter of `OtpContract` causing `java.lang.NullPointerException: Parameter specified as non-null is null`.
To fix this we use kotlin extension for `launch` for `ActivityResultLauncher<Unit>` and don't need to pass any input parameter.
See change-log for [androidx.activity 1.2.0-alpha05](https://developer.android.com/jetpack/androidx/releases/activity#1.2.0-alpha05)
> Kotlin extensions for launch have been added to the androidx.activity.result package for ActivityResultLauncher<Void> and ActivityResultLauncher<Unit> that remove the need to pass in null or Unit, respectively, mirroring that behavior from the previously invoke() extensions. ([aosp/1304674](https://android-review.googlesource.com/1304674), …

[AndroidDemo] use ActivityResultLauncher<Unit>.launch extension

---

.github/workflows/android.yml
.github/workflows/scan.yml

Using JDK 11 in our setup-java automatically installs the latest JDK, which is currently 11.0.17 (see https://www.java.com/en/releases/).
This version has an issue with javadoc builds, described here: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8222091
Using this version to build yubikit-android fails our CI builds, this PR pins the JDK to the latest version without the issue - 11.0.16.

Pin JDK version to 11.0.16

---

AndroidDemo/src/main/java/com/yubico/yubikit/android/app/ui/management/ManagementFragment.kt
AndroidDemo/src/main/java/com/yubico/yubikit/android/app/ui/management/ManagementViewModel.kt
android/src/main/java/com/yubico/yubikit/android/transport/nfc/NfcSmartCardConnection.java
android/src/main/java/com/yubico/yubikit/android/transport/usb/connection/UsbSmartCardConnection.java
core/src/main/java/com/yubico/yubikit/core/smartcard/SmartCardConnection.java

Adds `public byte[] getAtr()` method to the SmartCardConnection interface for getting [Answer to Reset](https://en.wikipedia.org/wiki/Answer_to_reset). Implements the functionality for USB and NFC smart card connections.
Updates AndroidDemo application with example usage.

Add ATR/ATS getter to SmartCardConnection

---

android/src/main/java/com/yubico/yubikit/android/transport/nfc/NfcYubiKeyDevice.java

Android 13 introduced the following change:
- when accessing a nfc tag which is no longer connected, throw a SecurityException (see [commit](https://android.googlesource.com/platform/frameworks/base/+/113f3a4a1d9171db7456aa9ae8b0a2b50545c326%5E%21/)). 
Stack trace for reference:
```
java.lang.SecurityException: Permission Denial: Tag ( ID: 27 AB A7 25 01 A7 AB ) is out of date
at android.nfc.Tag.getTagService(Tag.java:381)
at android.nfc.tech.BasicTagTechnology.isConnected(BasicTagTechnology.java:63)
at android.nfc.tech.IsoDep.isConnected(IsoDep.java:40)
at com.yubico.yubikit.android.transport.nfc.NfcYubiKeyDevice.lambda$remove$0$com-yubico-yubikit-android-transport-nfc-NfcYubiKeyDevice(NfcYubiKeyDevice.java:102)
```
I couldn't find any official documentation for this, but the commit. #79 …

Catch SecurityException when NFC key is removed

---

AndroidDemo/src/main/java/com/yubico/yubikit/android/app/ui/management/ManagementFragment.kt
AndroidDemo/src/main/java/com/yubico/yubikit/android/app/ui/management/ManagementViewModel.kt
android/src/main/java/com/yubico/yubikit/android/transport/nfc/NfcYubiKeyDevice.java
support/src/main/java/com/yubico/yubikit/support/DeviceUtil.java
support/src/main/java/com/yubico/yubikit/support/UnknownKeyException.java

It is simple to verify that a USB device is known YubiKey by comparing the USB PID values. Because this is a bit more complicated for NFC devices, this PR adds two different methods which clients can use to verify that the NFC connection was created by YubiKey.
1. `DeviceUtil.readInfo(YubiKeyConnection connection, UsbPid)` will throw `UnknownKeyException` if the device connected through `connection` is not manufactured by Yubico. To use this method, one needs to add dependency to the `:support` module which might not be ideal.
2. `bool NfcYubiKeyDevice.isYubiKey()` will return `true` if the device is manufactured by Yubico. The disadvantage of this method is that it opens several sessions (Management and YubiOTP) on the NFC device, which might degrade the performance if used every time …

Is NFC device a Yubico key?

---

android/src/main/java/com/yubico/yubikit/android/transport/nfc/NfcYubiKeyDevice.java

Exceptions which happened during openConnection and were not IOExceptions were swallowed by the task and never reported as a failure Result to the callback. 
This fix makes sure that any exception will be reported in the callback as an IOException, so that the callback can handle it.

Handle all exceptions when opening NFC connections

---

AndroidDemo/src/main/java/com/yubico/yubikit/android/app/ui/management/ManagementViewModel.kt

When an unknown device is used with the Demo App, the views could still show information from previously connected keys, such as enabled capabilities checkboxes. This is fixed by cleaning the livedata in exceptional conditions.

[AndroidDemo] Update management screen properly for unknown devices.

---

.github/workflows/android.yml

Because of an issue in Java 11.0.17 (https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8222091) the version of JDK we used in our GitHub action was pinned to 11.0.16. This PR reverts this pinning, as the issue was fixed in 11.0.18. 
This PR also switches to use Eclipse Adoptium OpenJDK for building yubikit on GitHub.

Unpin JDK version

---

android/src/main/java/com/yubico/yubikit/android/transport/nfc/NfcSmartCardConnection.java
android/src/main/java/com/yubico/yubikit/android/transport/usb/UsbDeviceManager.java
android/src/main/java/com/yubico/yubikit/android/transport/usb/UsbYubiKeyDevice.java
android/src/main/java/com/yubico/yubikit/android/transport/usb/UsbYubiKeyManager.java
android/src/main/java/com/yubico/yubikit/android/transport/usb/connection/UsbSmartCardConnection.java
android/src/main/java/com/yubico/yubikit/android/transport/usb/connection/UsbYubiKeyConnection.java
android/src/main/java/com/yubico/yubikit/android/ui/YubiKeyPromptActivity.java
android/src/main/java/com/yubico/yubikit/android/ui/YubiKeyPromptConnectionAction.java
core/src/main/java/com/yubico/yubikit/core/Logger.java
core/src/main/java/com/yubico/yubikit/core/application/CommandState.java
core/src/main/java/com/yubico/yubikit/core/fido/FidoProtocol.java
core/src/main/java/com/yubico/yubikit/core/internal/Logger.java
core/src/main/java/com/yubico/yubikit/core/internal/package-info.java
core/src/main/java/com/yubico/yubikit/core/otp/OtpProtocol.java
management/src/main/java/com/yubico/yubikit/management/ManagementSession.java
oath/src/main/java/com/yubico/yubikit/oath/OathSession.java
piv/src/main/java/com/yubico/yubikit/piv/PivSession.java
piv/src/main/java/com/yubico/yubikit/piv/jca/PivCipherSpi.java
piv/src/main/java/com/yubico/yubikit/piv/jca/PivProvider.java
support/src/main/java/com/yubico/yubikit/support/DeviceUtil.java
yubiotp/src/main/java/com/yubico/yubikit/yubiotp/YubiOtpSession.java

We are in the state of deprecating `core.Logger` class in favor of `slf4j`. Internally in the libraries we use adapting calls (`Logger.debug(logger, msg)` etc.) which were added into the public `Logger` interface. This works great, but creates a lot of warnings that the libraries use deprecated class. The amount of the warnings might cause that we overlook an important warning.
This PR moves out the methods into a new _internal_ class. This effectively removes the warnings when using `core.internal.Logger.debug(logger, msg)` and similar calls.
This class has a javadoc informing that it should not be used by applications and is in a new `internal` package. It will be removed together with the deprecated `core.Logger` in the next major library release.

Add core.internal.Logger

---

.github/workflows/android.yml
.github/workflows/scan.yml
AndroidDemo/build.gradle
android/build.gradle
build.gradle
buildSrc/build.gradle
buildSrc/src/main/groovy/project-convention-java-library.gradle
buildSrc/src/main/groovy/project-convention-logging.gradle
buildSrc/src/main/groovy/project-convention-spotbugs.gradle
buildSrc/src/main/groovy/yubikit-java-library.gradle
core/build.gradle
gradle/wrapper/gradle-wrapper.properties
management/build.gradle
oath/build.gradle
piv/build.gradle
piv/src/test/java/com/yubico/yubikit/piv/GzipUtilsTest.java
piv/src/test/java/com/yubico/yubikit/piv/KeyTypeTest.java
publish.gradle
support/build.gradle
testing-android/build.gradle
testing/build.gradle
yubiotp/build.gradle

The SDK was using outdated dependencies, this PR updated the project dependencies (gradle, android gradle plugin, **spotbugs**, testing libraries).
Other improvements:
- added `buildSrc` which contains groovy plugins which are reused by the modules (logging, spotbugs, java compile options such as `targetCompatibility`/`sourceCompatibility`). The plugins are:
-  `project-convention-java-library` - sets common compile options and dependencies
-  `project-convention-logging` - sets dependencies for logging
-  `project-convention-spotbugs` - sets options for spotbugs
-  `yubikit-java-library` - uses the previous and is the plugin included in the java libraries
- reviewed spotbugs plugin we use and added html output, which will be present in the artifacts. 
- updated compatibility with jdk17

Build system updates

---

android/src/main/java/com/yubico/yubikit/android/transport/usb/UsbDeviceManager.java

Android 14 introduces behaviour changes for all apps and apps targeting Android 14. After review only the following behaviour changes needed to be updated:
- [Security - Restrictions to implicit and pending intents](https://developer.android.com/about/versions/14/behavior-changes-14#safer-intents)
- [Security - Runtime-registered broadcasts receivers must specify export behavior](https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported)
This PR adapts YubiKit with the needed changes. Tested with Android 14 Beta 2.

Adapt to Android 14

---

AndroidDemo/src/main/java/com/yubico/yubikit/android/app/ui/piv/PivCertificateFragment.kt
android/src/main/res/values/strings.xml
core/src/main/java/com/yubico/yubikit/core/application/InvalidPinException.java
core/src/main/java/com/yubico/yubikit/core/fido/CtapException.java
core/src/main/java/com/yubico/yubikit/core/keys/EllipticCurveValues.java
core/src/main/java/com/yubico/yubikit/core/keys/PrivateKeyValues.java
core/src/main/java/com/yubico/yubikit/core/keys/PublicKeyValues.java
core/src/main/java/com/yubico/yubikit/core/keys/package-info.java
core/src/main/java/com/yubico/yubikit/core/smartcard/Apdu.java
core/src/main/java/com/yubico/yubikit/core/smartcard/SmartCardProtocol.java
core/src/main/java/com/yubico/yubikit/core/util/ByteUtils.java
core/src/test/java/com/yubico/yubikit/core/keys/PrivateKeyValuesTest.java
core/src/test/java/com/yubico/yubikit/core/keys/PublicKeyValuesTest.java
piv/src/main/java/com/yubico/yubikit/piv/KeyType.java
piv/src/main/java/com/yubico/yubikit/piv/Padding.java
piv/src/main/java/com/yubico/yubikit/piv/PivSession.java
piv/src/main/java/com/yubico/yubikit/piv/Slot.java
piv/src/main/java/com/yubico/yubikit/piv/SlotMetadata.java
piv/src/main/java/com/yubico/yubikit/piv/jca/PivKeyAgreementSpi.java
piv/src/main/java/com/yubico/yubikit/piv/jca/PivPrivateKey.java
settings.gradle
testing-android/build.gradle
testing-android/src/main/java/com/yubico/yubikit/testing/TestActivity.java

This PR mainly changes how public and private keys are used in the SDK to allow for usage (mainly in PivSession) without requiring a JCA SecurityProvider with the needed algorithms, unless cryptographic operations need to be used. It comes with some deprecations to be removed in the next major version of this project.

Refactor handling of asymmetric keys

---

android/src/main/java/com/yubico/yubikit/android/transport/usb/UsbDeviceManager.java
android/src/main/java/com/yubico/yubikit/android/ui/YubiKeyPromptActivity.java

Updates yubikit to use type-safer methods:
[`Intent.getParcelableExtra(String)`](https://developer.android.com/reference/android/content/Intent#getParcelableExtra(java.lang.String)) -> [`Intent.getParcelableExtra(String, Class)`](https://developer.android.com/reference/android/content/Intent#getParcelableExtra(java.lang.String,%20java.lang.Class%3CT%3E))
[`Bundle.getSerializable(String)`](https://developer.android.com/reference/android/os/Bundle#getSerializable(java.lang.String)) -> [`Bundle.getSerializable(String, Class)`](https://developer.android.com/reference/android/os/Bundle#getSerializable(java.lang.String,%20java.lang.Class%3CT%3E))

Use new APIs on Android 13+

---

fido/src/test/java/com/yubico/yubikit/fido/CborTest.java

This change uses JUnit's Parametrized test runner to supply test values. The original test set was split by categories (Integers, Strings, Lists and Maps) to form smaller groups.
Only features supported by our `Cbor` implementation are tested.

[fido] refactor CBOR unit tests

---

AndroidDemo/build.gradle
android/build.gradle
android/publish.gradle
build.gradle
buildSrc/src/main/groovy/project-convention-spotbugs.gradle
gradle/wrapper/gradle-wrapper.properties
testing-android/build.gradle
testing-android/src/androidTest/java/com/yubico/yubikit/testing/fido/BasicWebAuthnClientInstrumentedTests.java
testing-android/src/androidTest/java/com/yubico/yubikit/testing/fido/Ctap2CredentialManagementInstrumentedTests.java
testing-android/src/androidTest/java/com/yubico/yubikit/testing/fido/Ctap2SessionInstrumentedTests.java
testing-android/src/androidTest/java/com/yubico/yubikit/testing/fido/EnterpriseAttestationInstrumentedTests.java
testing-android/src/main/java/com/yubico/yubikit/testing/TestActivity.java
testing-android/src/main/java/com/yubico/yubikit/testing/framework/YKInstrumentedTests.java
testing-android/src/main/res/layout/test_activity.xml

Bumps dependencies and build options of the SDK. The most significant are:
- `targetSdk` of the SDK is now 34
- built with Gradle 8.3 and AGP 8.1.2
Other fixes include resolving deprecations in the build system and instrumented tests.

Bump dependencies 

---

.github/workflows/android.yml
.github/workflows/spotbugs-scan.yml
android/build.gradle
build.gradle
buildSrc/build.gradle
buildSrc/src/main/groovy/project-convention-spotbugs.gradle

This PR is to test whether uploading SARIF files generated by spotbugs applies found vulnerabilities in the Security/Code Scanning GitHub section. (No effect have been seen when this running in branch)
- SpotBugs related gradle code is moved to `project-convention-spotbugs.gradle`
- Produced SARIF files are uploaded to GitHub for analysis
- Produced HTML files are available to browse locally when using `./gradlew spotbugsMain spotbugsRelease --rerun-tasks`
Note: the `Fix Sarif` step uses `jq` to update the sarif format to be closer to the [GitHub specification](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#providing-data-to-track-code-scanning-alerts-across-runs) but I did not see any effect if required parameters …

Add SpotBugs code scanning

---

fido/src/main/java/com/yubico/yubikit/fido/client/BasicWebAuthnClient.java
testing-android/src/androidTest/java/com/yubico/yubikit/testing/fido/BasicWebAuthnClientInstrumentedTests.java
testing-android/src/androidTest/java/com/yubico/yubikit/testing/fido/UvDiscouragedInstrumentedTests.java
testing/src/main/java/com/yubico/yubikit/testing/fido/BasicWebAuthnClientTests.java

Pass correct values of pinUvAuthParam and pinUvAuthProtocol to makeCredential.
Before this fix, we wrongly passed `0` pinUvAuthProtocol value instead of `null`. 
The new integration test verify makeCredential and getAssertion with `null` PIN and UserVerificationRequirement.DISCOURAGED. This way it is possible to create rk = true and rk = false credentials on FIDO2 keys which don't have PIN set. FIDO2 keys with set PIN will return `0x36` PIN_REQUIRED error.

Fix MC/GA UserVerificationRequirement.DISCOURAGED

---

management/src/main/java/com/yubico/yubikit/management/DeviceConfig.java
management/src/main/java/com/yubico/yubikit/management/DeviceInfo.java
management/src/main/java/com/yubico/yubikit/management/ManagementSession.java
management/src/test/java/com/yubico/yubikit/management/DeviceConfigBuilderTest.java
management/src/test/java/com/yubico/yubikit/management/DeviceInfoBuilderTest.java
support/src/main/java/com/yubico/yubikit/support/DeviceUtil.java
support/src/test/java/com/yubico/yubikit/support/Util.java

- Implements Builder design pattern for DeviceInfo and deprecates existing constructors.
- Adds support for reading DeviceConfig data from all existing pages.
- Adds missing unit tests for both DeviceConfig and DeviceInfo classes.

Improve DeviceInfo and DeviceConfig

---

AndroidDemo/build.gradle
AndroidDemo/src/main/java/com/yubico/yubikit/android/app/ui/oath/OathFragment.kt
oath/build.gradle
oath/src/main/java/com/yubico/yubikit/oath/Base32.java
oath/src/main/java/com/yubico/yubikit/oath/CredentialData.java
oath/src/test/java/com/yubico/yubikit/oath/Base32Test.java

In the latest version of commons-codec 1.16.1, Android incompatible changes have been introduced. Replaces Apache commons-codec base32 implementation with our own.  We only used that dependency for base32 secret handling in the OATH code.

Implement RFC 4648 Base32 Encoding

---

AndroidDemo/src/main/java/com/yubico/yubikit/android/app/MainActivity.kt
AndroidDemo/src/main/java/com/yubico/yubikit/android/app/ui/piv/PivCertificateFragment.kt
AndroidDemo/src/main/java/com/yubico/yubikit/android/app/ui/piv/PivViewModel.kt
AndroidDemo/src/main/res/layout/fragment_piv_certifiate.xml
AndroidDemo/src/main/res/values/strings.xml
core/src/main/java/com/yubico/yubikit/core/keys/PrivateKeyValues.java
piv/build.gradle
piv/src/main/java/com/yubico/yubikit/piv/KeyType.java
piv/src/main/java/com/yubico/yubikit/piv/PivSession.java
piv/src/main/java/com/yubico/yubikit/piv/jca/PivEcSignatureSpi.java
piv/src/main/java/com/yubico/yubikit/piv/jca/PivKeyAgreementSpi.java
piv/src/main/java/com/yubico/yubikit/piv/jca/PivKeyPairGeneratorSpi.java
piv/src/main/java/com/yubico/yubikit/piv/jca/PivKeyStoreSpi.java
piv/src/main/java/com/yubico/yubikit/piv/jca/PivPrivateKey.java
piv/src/main/java/com/yubico/yubikit/piv/jca/PivProvider.java
piv/src/test/java/com/yubico/yubikit/piv/PivProviderTest.java
testing-android/src/androidTest/java/com/yubico/yubikit/testing/piv/PivJcaProviderTests.java
testing-android/src/androidTest/java/com/yubico/yubikit/testing/piv/PivTests.java
testing/src/main/java/com/yubico/yubikit/testing/piv/PivCertificateTests.java
testing/src/main/java/com/yubico/yubikit/testing/piv/PivDeviceTests.java
testing/src/main/java/com/yubico/yubikit/testing/piv/PivJcaDecryptTests.java
testing/src/main/java/com/yubico/yubikit/testing/piv/PivJcaDeviceTests.java
testing/src/main/java/com/yubico/yubikit/testing/piv/PivJcaSigningTests.java
testing/src/main/java/com/yubico/yubikit/testing/piv/PivJcaUtils.java
testing/src/main/java/com/yubico/yubikit/testing/piv/PivMoveKeyTests.java
testing/src/main/java/com/yubico/yubikit/testing/piv/PivTestUtils.java

- Generate/import Ed25519 and X25519 keys directly through `PivSession` or with the use of our YKPiv JCA Provider. 
- Digital signature with Ed25519 through YKPiv JCA Provider.
- Key agreement with X25519 through YKPiv JCA Provider.
- Both new types can be stored in all of the PIV slots.
- All operations on the new key types are guarded by `FEATURE_CV25519` feature.
- New tests for the key types, including different order of JCA providers.
Other changes:
- Cache management key type in the PivSession object for simpler coding, use `PivSession.getManagementKeyType()` to get the value.
- Deprecated `PivSession.authenticate(ManagementKeyType,byte[])` and added `PivSession.authenticate(byte[])` - this new method uses the cached key directly.
- Updated DemoApplication so that one can generate …

Support Ed25519 and X25519

---

management/src/main/java/com/yubico/yubikit/management/DeviceConfig.java
management/src/main/java/com/yubico/yubikit/management/DeviceInfo.java
management/src/test/java/com/yubico/yubikit/management/DeviceInfoTest.java
testing/src/main/java/com/yubico/yubikit/testing/management/ManagementDeviceTests.java

Fixes following:
- STM and FPS versions, parsed as `0.0.0` will be treated as `null`.
- Fix to default value of `nfcRestricted`
- Change of type of `partNumber` to be nullable

Fix minor DeviceInfo issues

---

.github/workflows/spotbugs-scan.yml

Uploads each sarif file with its own category and fixes the following warning: 
```
Uploading multiple SARIF runs with the same category is deprecated and will be removed on June 4, 2025. Please update your workflow to upload a single run per category.
```
More info: https://github.blog/changelog/2024-05-06-code-scanning-will-stop-combining-runs-from-a-single-upload

Categorize sarif files

---

.github/workflows/spotbugs-scan.yml
buildSrc/build.gradle
buildSrc/src/main/groovy/project-convention-spotbugs.gradle

1. Bumps the versions of spotbugs and spotbugs gradle plugin to most recent.
2. Forces `true` result for the spotbugs invocations (in the sarif files this is a property in `runs[].invocations` called `executionSuccessful`). The reason is that there is a bug in find-sec-bugs which causes warnings/errors similar to
```
The following classes needed for analysis were missing:
call
invoke
```
and makes the invocation to fail (with exit code 3 and execution successful `false`). 
Github is reading the value of `executionSuccessful` and reports it as 
Forcing execution successful to true removes the error status and we can still browse all the reports in the security scanning view.

Update Spotbugs GitHub action

---

core/src/main/java/com/yubico/yubikit/core/application/Feature.java
core/src/main/java/com/yubico/yubikit/core/application/SessionVersionOverride.java
support/src/main/java/com/yubico/yubikit/support/DeviceUtil.java
testing-android/src/androidTest/java/com/yubico/yubikit/testing/oath/OathTests.java
testing-android/src/main/java/com/yubico/yubikit/testing/framework/FidoInstrumentedTests.java
testing-android/src/main/java/com/yubico/yubikit/testing/framework/MpeInstrumentedTests.java
testing-android/src/main/java/com/yubico/yubikit/testing/framework/OathInstrumentedTests.java
testing-android/src/main/java/com/yubico/yubikit/testing/framework/OpenPgpInstrumentedTests.java
testing-android/src/main/java/com/yubico/yubikit/testing/framework/PivInstrumentedTests.java
testing-android/src/main/java/com/yubico/yubikit/testing/framework/SecurityDomainInstrumentedTests.java
testing-android/src/main/java/com/yubico/yubikit/testing/framework/YKInstrumentedTests.java
testing/src/main/java/com/yubico/yubikit/testing/TestState.java
testing/src/main/java/com/yubico/yubikit/testing/fido/FidoTestState.java
testing/src/main/java/com/yubico/yubikit/testing/mpe/MpeTestState.java
testing/src/main/java/com/yubico/yubikit/testing/oath/OathDeviceTests.java
testing/src/main/java/com/yubico/yubikit/testing/oath/OathTestState.java
testing/src/main/java/com/yubico/yubikit/testing/openpgp/OpenPgpDeviceTests.java
testing/src/main/java/com/yubico/yubikit/testing/openpgp/OpenPgpTestState.java
testing/src/main/java/com/yubico/yubikit/testing/piv/PivJcaDeviceTests.java
testing/src/main/java/com/yubico/yubikit/testing/piv/PivTestState.java
testing/src/main/java/com/yubico/yubikit/testing/sd/SecurityDomainTestState.java

Improves handling of legacy YubiKeys. Changes in SDK code:
- `Feature.isSupported` will no longer return true for major version 0.
- `DeviceUtil.readInfo` has a new override which accepts ScpKeyParameters to allow reading info over secure connections.
A big part of this PR are updates to device tests which discovered issues with NEO keys: 
- The test code was trying to open ManagementSession directly on any connection, which is not possible on NEO. Instead we need to use `DeviceUtil.readInfo` to synthesize the DeviceInfo without Management session and for some situations this session has to be opened in SCP mode. As a consequence of this, platform tests have to pass a UsbPid for USB connected YubiKeys to be able to call readInfo.
- NEO's applications use their own version numbers which …

Improve legacy key support

---

fido/src/main/java/com/yubico/yubikit/fido/client/CredentialManager.java
fido/src/main/java/com/yubico/yubikit/fido/ctap/CredentialManagement.java
testing-android/src/androidTest/java/com/yubico/yubikit/testing/fido/Ctap2CredentialManagementInstrumentedTests.java
testing/src/main/java/com/yubico/yubikit/testing/fido/BasicWebAuthnClientTests.java
testing/src/main/java/com/yubico/yubikit/testing/fido/Ctap2CredentialManagementTests.java

See the [specification](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#authenticatorCredentialManagement) 
This PR also adds tests of both the CTAP2 call and client call.

[FIDO2] Implement updateUserInformation sub command of authenticatorCredentialManagement

---

android/src/main/java/com/yubico/yubikit/android/transport/nfc/NfcYubiKeyDevice.java
android/src/main/java/com/yubico/yubikit/android/transport/usb/UsbYubiKeyDevice.java

Fixes #158 
This unifies exception handling during `UsbYubiKeyDevice.requestConnection`. As the linked issue points out, any `Exception` which is not an `IOException` in not propagate throughout the `Result` to the caller.
The behavior has been updated to be same as in NfcYubiKeyDevice.

Propagate exceptions 

---

core/src/main/java/com/yubico/yubikit/core/UsbInterface.java
core/src/main/java/com/yubico/yubikit/core/fido/FidoProtocol.java
management/src/main/java/com/yubico/yubikit/management/ManagementSession.java
support/src/main/java/com/yubico/yubikit/support/DeviceUtil.java

This PR adds additional handling of devices with FW < 4. 
With these improvements, such devices will get:
- Correct ManagementSession version over FidoConnection.
- Correct USB interfaces value (OTP, FIDO, CCID) during NFC connections.
The changes has been tested with YubiKey Neo.

Improve functionality for legacy devices

---

core/src/main/java/com/yubico/yubikit/core/smartcard/SW.java
core/src/main/java/com/yubico/yubikit/core/smartcard/SmartCardProtocol.java
testing-android/src/androidTest/java/com/yubico/yubikit/testing/neo/NeoTests.java
testing-android/src/main/java/com/yubico/yubikit/testing/framework/NeoInstrumentedTests.java
testing-android/src/main/java/com/yubico/yubikit/testing/framework/YKInstrumentedTests.java
testing/src/main/java/com/yubico/yubikit/testing/neo/NeoDeviceTests.java

All NEO's I tested return 0x6A81 (FUNCTION_NOT_SUPPORTED) when trying to select the management app. 
This PR makes this situation an ApplicationNotAvailableException.
Fixes #173

Treat FUNCTION_NOT_SUPPORTED as ApplicationNotAvailableException

---

management/src/main/java/com/yubico/yubikit/management/ManagementSession.java

Improves handling of versionQualifier when constructing ManagementSession by using the qualifier version also for FIDO and OTP connections, where previously this was only handled during SmartCard connections.
This has been tested with integration tests over USB and NFC, on Android 8.1.0 and Android 16 and YubiKeys 3 to latest.

Use version qualifier for all protocols

---

fido/src/main/java/com/yubico/yubikit/fido/client/extensions/LargeBlobExtension.java

- Fixes issue when the SDK was using wrong property name for authenticator inputs. `largeBlob` instead of `largeBlobKey`.
- Fixes support detection
See https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#sctn-largeBlobKey-extension
Testing: Integration tests pass on devices supporting largeBlobKey

[FIDO] fix largeBlobKey authenticator inputs

---

testing-android/src/androidTest/java/com/yubico/yubikit/testing/fido/Ctap2BioEnrollmentInstrumentedTests.java
testing-android/src/androidTest/java/com/yubico/yubikit/testing/fido/FidoTests.java
testing-desktop/src/integrationTest/java/com/yubico/yubikit/testing/desktop/fido/Ctap2BioEnrollmentInstrumentedTests.java
testing-desktop/src/integrationTest/java/com/yubico/yubikit/testing/desktop/fido/FidoTests.java
testing/src/main/java/com/yubico/yubikit/testing/fido/Ctap2BioEnrollmentTests.java
testing/src/main/java/com/yubico/yubikit/testing/fido/Ctap2BioUVTests.java
testing/src/main/java/com/yubico/yubikit/testing/fido/Ctap2BioUvTests.java
testing/src/main/java/com/yubico/yubikit/testing/fido/utils/BioEnrollment.java
testing/src/main/java/com/yubico/yubikit/testing/fido/utils/ClientHelper.java
testing/src/main/java/com/yubico/yubikit/testing/fido/utils/CreationOptionsBuilder.java

This pull request introduces a new manual test to verify PIN fallback after biometric user verification (UV) is blocked, refactors fingerprint enrollment helper methods into a new utility class, and improves test code maintainability and clarity. The changes affect both Android and desktop test suites, as well as core test utilities.

[FIDO] Add device test to verify PIN fallback after UV_BLOCKED
