Yubico/yubikit-android

- .github/workflows/android.yml
Just build of 2 flavors and run UTs on release build
> Create GitHub actions build automation

- yubikit/src/test/java/com/yubico/yubikit/YubikitManagerTest.java
interface of USB discovery callback has changed
> Fix ut build

- oath/src/main/java/com/yubico/yubikit/oath/qr/QrActivity.java
In case if user tries to use it on the phone without Google play services this API won't work.
And there are couple other error scenarios that we'd prefer to close activity with error result rather than swallowing it.
> Update qr activity to check for potential errors and return error code

- support/src/main/java/com/yubico/yubikit/support/DeviceUtil.java
Yubikit-android has minSdkVersion set to 19.
The new `:support` module used Java 1.8 features which were are not supported on Android API 19. This causes crashes in runtime on older devices.
This PR replaces the not supported features with their working equivalents.
| Feature | Available from Android API level |
| -------- | ------------ |
| Optional | 24 |
| StringJoiner | 24 |
| Map#replace(key, value) | 24 |
> Replace not supported APIs

- .github/workflows/scan.yml
Migrating off the old scanning tool onto CodeQL
> Updating to use CodeQL 

- piv/jca.adoc
Adds a guide with example snippets
> Documentation for PIV JCA

- .github/workflows/android.yml
- .idea/scopes/Documentation.xml
- NEWS
- README.adoc
- android/README.adoc
- android/publish.gradle
- build.gradle
- core/README.adoc
- doc/Migration_1.0-2.0.adoc
- doc/publish.adoc
- piv/README.adoc
- piv/piv_jca.adoc
- publish.gradle
- support/README.adoc
- testing-android/README.adoc
Merges changes done in the release branch.
- version string was updated to 2.2.0-SNAPSHOT
> Merge release 2.1.0 branch

- android/src/main/res/values/colors.xml
- android/src/main/res/values/styles.xml
> Add yubikit prefix to color resources

- AndroidDemo/build.gradle
- android/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- testing-android/build.gradle
Updates project to use and target latest Android SDK (33), bumps used dependencies libraries to  latest versions.
> Update build / dependencies

- AndroidDemo/src/main/java/com/yubico/yubikit/android/app/ui/management/ManagementFragment.kt
- AndroidDemo/src/main/java/com/yubico/yubikit/android/app/ui/management/ManagementViewModel.kt
- NEWS
- android/src/main/java/com/yubico/yubikit/android/transport/nfc/NfcYubiKeyDevice.java
- build.gradle
- support/src/main/java/com/yubico/yubikit/support/DeviceUtil.java
- support/src/test/java/com/yubico/yubikit/support/Util.java
Merges changes from release branch + bumps to version 2.3.0-SNAPSHOT
> Merge release 2.2.0

- piv/build.gradle
- piv/src/main/java/com/yubico/yubikit/piv/GzipUtils.java
- piv/src/main/java/com/yubico/yubikit/piv/PivSession.java
- piv/src/test/java/com/yubico/yubikit/piv/GzipUtilsTest.java
- testing-android/src/androidTest/java/com/yubico/yubikit/testing/PivTests.java
- testing/src/main/java/com/yubico/yubikit/testing/piv/PivCertificateTests.java
- testing/src/main/java/com/yubico/yubikit/testing/piv/PivJcaDeviceTests.java
Adds support for GZIP compressed PIV certificates (as specified in NIST.SP.800-73-4).
> Support compressed PIV certificates

- core/src/main/java/com/yubico/yubikit/core/fido/FidoProtocol.java
- fido/src/main/java/com/yubico/yubikit/fido/client/BasicWebAuthnClient.java
- fido/src/main/java/com/yubico/yubikit/fido/ctap/ClientPin.java
- fido/src/main/java/com/yubico/yubikit/fido/ctap/Ctap2Session.java
- fido/src/main/java/com/yubico/yubikit/fido/ctap/PinUvAuthDummyProtocol.java
- fido/src/main/java/com/yubico/yubikit/fido/webauthn/AttestationObject.java
- testing-android/src/androidTest/java/com/yubico/yubikit/testing/fido/EnterpriseAttestationInstrumentedTests.java
- testing/src/main/java/com/yubico/yubikit/testing/fido/Ctap2ClientPinTests.java
- testing/src/main/java/com/yubico/yubikit/testing/fido/EnterpriseAttestationTests.java
Each commit fixes a specific issue with my CTAP2.1 implementation.
> CTAP2.1 improvements

- openpgp/src/main/java/com/yubico/yubikit/openpgp/Kdf.java
- openpgp/src/main/java/com/yubico/yubikit/openpgp/OpenPgpSession.java
- openpgp/src/main/java/com/yubico/yubikit/openpgp/PrivateKeyTemplate.java
- openpgp/src/main/java/com/yubico/yubikit/openpgp/Pw.java
- testing-android/src/main/java/com/yubico/yubikit/testing/TestActivity.java
- testing-android/src/main/java/com/yubico/yubikit/testing/framework/YKInstrumentedTests.java
- testing-android/src/main/res/values/strings.xml
- testing/src/main/java/com/yubico/yubikit/testing/openpgp/OpenPgpDeviceTests.java
- changes the data type for PINs from String to char[] and erases memory after use
- PrivateKeyTemplate implements Destroyable
- fixes to device test so that the phone screen shows correct test information
> Improve handling of sensitive data

- openpgp/src/main/java/com/yubico/yubikit/openpgp/OpenPgpSession.java
- testing/src/main/java/com/yubico/yubikit/testing/piv/PivTestUtils.java
- updates openpgp verifyUserPin javadoc
- updates static keys used for PIV device tests
> Fix docs and tests

- fido/src/main/java/com/yubico/yubikit/fido/ctap/Config.java
- testing-android/src/androidTest/java/com/yubico/yubikit/testing/fido/Ctap2ConfigInstrumentedTests.java
- testing/src/main/java/com/yubico/yubikit/testing/fido/Ctap2ConfigTests.java
> Fix setMinPinLength implementation

- core/src/main/java/com/yubico/yubikit/core/smartcard/SW.java
- piv/src/main/java/com/yubico/yubikit/piv/PivSession.java
- testing-android/src/androidTest/java/com/yubico/yubikit/testing/piv/PivJcaProviderTests.java
- testing/src/main/java/com/yubico/yubikit/testing/piv/PivMoveKeyTests.java
Implements `INS_MOVE_KEY` which is used to move and delete private key from a specific slot.
> [PIV] Add support for moving and deleting keys

- management/src/main/java/com/yubico/yubikit/management/Capability.java
- management/src/main/java/com/yubico/yubikit/management/DeviceConfig.java
- management/src/main/java/com/yubico/yubikit/management/DeviceInfo.java
- management/src/test/java/com/yubico/yubikit/management/DeviceConfigBuilderTest.java
- management/src/test/java/com/yubico/yubikit/management/DeviceConfigTest.java
- management/src/test/java/com/yubico/yubikit/management/DeviceInfoBuilderTest.java
- management/src/test/java/com/yubico/yubikit/management/DeviceInfoTest.java
- management/src/test/java/com/yubico/yubikit/management/TestUtil.java
- testing-android/src/androidTest/java/com/yubico/yubikit/testing/management/ManagementTests.java
- testing-android/src/main/java/com/yubico/yubikit/testing/framework/ManagementInstrumentedTests.java
- testing/src/main/java/com/yubico/yubikit/testing/management/ManagementDeviceTests.java
- adds read support for properties in new FW
- adds r/w support for NFC_RESTRICTED (0x17) tag value in DeviceConfig
- updates unit and device tests
> Add support for DeviceInfo properties of new fw.

- NEWS
- build.gradle
- core/src/main/java/com/yubico/yubikit/core/application/Feature.java
- core/src/main/java/com/yubico/yubikit/core/application/SessionVersionOverride.java
- core/src/main/java/com/yubico/yubikit/core/fido/FidoProtocol.java
- core/src/main/java/com/yubico/yubikit/core/util/RandomUtils.java
- doc/security_domain.adoc
- fido/src/main/java/com/yubico/yubikit/fido/ctap/PinUvAuthProtocolV1.java
- fido/src/main/java/com/yubico/yubikit/fido/ctap/PinUvAuthProtocolV2.java
- piv/src/test/java/com/yubico/yubikit/piv/KeyTypeTest.java
- support/src/main/java/com/yubico/yubikit/support/DeviceUtil.java
- testing-android/src/androidTest/java/com/yubico/yubikit/testing/oath/OathTests.java
- testing-android/src/main/java/com/yubico/yubikit/testing/framework/FidoInstrumentedTests.java
- testing-android/src/main/java/com/yubico/yubikit/testing/framework/MpeInstrumentedTests.java
- testing-android/src/main/java/com/yubico/yubikit/testing/framework/OathInstrumentedTests.java
- testing-android/src/main/java/com/yubico/yubikit/testing/framework/OpenPgpInstrumentedTests.java
- testing-android/src/main/java/com/yubico/yubikit/testing/framework/PivInstrumentedTests.java
- testing-android/src/main/java/com/yubico/yubikit/testing/framework/SecurityDomainInstrumentedTests.java
- testing-android/src/main/java/com/yubico/yubikit/testing/framework/YKInstrumentedTests.java
- testing/src/main/java/com/yubico/yubikit/testing/TestState.java
- testing/src/main/java/com/yubico/yubikit/testing/fido/FidoTestState.java
- testing/src/main/java/com/yubico/yubikit/testing/mpe/MpeTestState.java
- testing/src/main/java/com/yubico/yubikit/testing/oath/OathDeviceTests.java
- testing/src/main/java/com/yubico/yubikit/testing/oath/OathTestState.java
- testing/src/main/java/com/yubico/yubikit/testing/openpgp/OpenPgpDeviceTests.java
- testing/src/main/java/com/yubico/yubikit/testing/openpgp/OpenPgpTestState.java
- testing/src/main/java/com/yubico/yubikit/testing/piv/PivJcaDeviceTests.java
- testing/src/main/java/com/yubico/yubikit/testing/piv/PivTestState.java
- testing/src/main/java/com/yubico/yubikit/testing/sd/SecurityDomainTestState.java
- yubiotp/src/main/java/com/yubico/yubikit/yubiotp/YubiOtpSession.java
+ bump version to 2.7.1-SNAPSHOT
> Merge release 2.7.0

- AndroidDemo/build.gradle
- android/build.gradle
- build.gradle
- buildSrc/build.gradle
- fido/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- testing-android/build.gradle
- testing/build.gradle
Updates to target Android 15 and bumps dependencies to newer versions.
Tested by running smoke integration tests on Android 15 and Android 8.0.1
> Update target SDK to 35 (Android 15)

- NEWS
- build.gradle
- testing-android/src/androidTest/java/com/yubico/yubikit/testing/piv/PivBioMultiProtocolTests.java
- testing-android/src/androidTest/java/com/yubico/yubikit/testing/piv/PivTests.java
- testing-desktop/src/integrationTest/java/com/yubico/yubikit/testing/desktop/piv/PivBioMultiProtocolTests.java
- testing-desktop/src/integrationTest/java/com/yubico/yubikit/testing/desktop/piv/PivTests.java
- testing/src/main/java/com/yubico/yubikit/testing/TestState.java
- testing/src/main/java/com/yubico/yubikit/testing/openpgp/OpenPgpDeviceTests.java
- testing/src/main/java/com/yubico/yubikit/testing/piv/PivJcaSigningTests.java
- testing/src/main/java/com/yubico/yubikit/testing/piv/PivTestState.java
Merges 2.8.0 updates and bumps version to 2.8.1-SNAPSHOT.
> Merge release 2.8.0

- fido/src/main/java/com/yubico/yubikit/fido/client/BasicWebAuthnClient.java
- testing/src/main/java/com/yubico/yubikit/testing/fido/BasicWebAuthnClientTests.java
This fixes reported issue when passing an allowList with non-existing credentials to getAssertion() resulted in multiple credentials. See added test for details.
> Handle allowList without existing credentials

- android/build.gradle
- buildSrc/src/main/groovy/project-convention-logging.gradle
- buildSrc/src/main/groovy/project-convention-spotbugs.gradle
This pull request updates several dependencies across the project to their latest versions, ensuring compatibility and access to new features or bug fixes. The most notable changes include updates to `mockito-core`, `slf4j-api`, and `findsecbugs-plugin`, as well as adjustments to SpotBugs-related dependencies.
> Dependency bump

- core/src/main/java/com/yubico/yubikit/core/otp/OtpProtocol.java
Fixes the way how programming sequence update is evaluated, only checking whether both slots are not programmed (both lowest bits have to be 0). 
This makes the implementation same as in our python sdk.
> [YubiOTP] Programming sequence update evaluation

- fido/src/main/java/com/yubico/yubikit/fido/client/BasicWebAuthnClient.java
- fido/src/main/java/com/yubico/yubikit/fido/client/UvInvalidClientError.java
Adds support for Bio keys to Webauthn client.
> [FIDO] add support support bio keys
